'''
This code was generated by chatGPT.
It assumes the day 1 input can be read from numbers.txt
'''
# Open the file and read its lines into a list
with open('numbers.txt', 'r') as f:
    lines = f.readlines()

# Initialize variables to keep track of the current total and the highest total
current_total = 0
highest_total = 0

# Iterate over the lines in the file
for line in lines:
    # Strip any leading or trailing whitespace from the line
    line = line.strip()

    # If the line is not empty, add the number to the current total
    if line:
        current_total += int(line)

    # If the line is empty, compare the current total to the highest total
    # and update the highest total if necessary
    else:
        if current_total > highest_total:
            highest_total = current_total

        # Reset the current total to 0 for the next set of numbers
        current_total = 0

# After all the lines have been processed, compare the final current total
# to the highest total and update the highest total if necessary
if current_total > highest_total:
    highest_total = current_total

# Print the highest total
print("The highest total is:", highest_total)
